#!/usr/bin/env python3
"""
Telegram Bot: Image ↔ C Header Converter
With webhooks – runs on Render Web Service (free) without needing keep‑alive.
Admin Chat ID: 5682792112
Time zone: Asia/Manila (UTC+8)
"""
import os
import sys
import logging
import tempfile
import zlib
import re
import asyncio
import time
from pathlib import Path
from collections import defaultdict
from datetime import datetime, timezone, timedelta

from telegram import Update, ReplyKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, filters, ContextTypes

# ----------------------------------------------
TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
if not TOKEN:
    print("❌ No TELEGRAM_BOT_TOKEN set! Please set the environment variable.")
    sys.exit(1)

ADMIN_CHAT_ID = 5682792112  # Your admin user ID

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Time zone for Manila (UTC+8)
MANILA_TZ = timezone(timedelta(hours=8))

# -------------------- KEYBOARD --------------------
def get_menu_keyboard():
    keyboard = [["Home", "Convert", "Commands"], ["Usage", "Profile"]]
    return ReplyKeyboardMarkup(keyboard, resize_keyboard=True, is_persistent=True)

# -------------------- CPU WORK --------------------
def generate_header_from_data(data: bytes, original_filename: str) -> bytes:
    crc = zlib.crc32(data)
    file_size = len(data)
    stem = re.sub(r'[^a-zA-Z0-9_]', '_', Path(original_filename).stem)
    array_name = stem + "_data"
    lines = [
        "// Automatically generated by Bitch.py",
        f"// Original file: {original_filename}",
        "// Credits: @Nyzism\n",
        f"unsigned char {array_name}[] = {{"
    ]
    chunk_size = 4096
    total_bytes = len(data)
    processed = 0
    hex_parts = []
    while processed < total_bytes:
        chunk = data[processed:processed+chunk_size]
        hex_parts.append(", ".join(f"0x{b:02X}" for b in chunk))
        processed += len(chunk)
    hex_lines = ",\n    ".join(hex_parts)
    lines.append(f"    {hex_lines}")
    lines.append("};")
    return "\n".join(lines).encode('utf-8')

def recover_image_from_header(content: str) -> tuple[bytes, str]:
    match = re.search(
        r'(?:const\s+uint8_t|unsigned\s+char)\s+(\w+)\s*\[\]\s*=\s*\{([^}]*)\};',
        content,
        re.DOTALL
    )
    if not match:
        raise ValueError("No array found")
    hex_bytes = re.findall(r'0x([0-9A-Fa-f]{2})', match.group(2))
    if not hex_bytes:
        raise ValueError("No hex data")
    data = bytearray(int(h, 16) for h in hex_bytes)
    name_match = re.search(r'// Original file:\s*(.+?)\s*\n', content)
    original_name = name_match.group(1).strip() if name_match else "recovered.png"
    return bytes(data), original_name

# -------------------- PROGRESS THROTTLING --------------------
progress_state = defaultdict(lambda: {"last_percent": -1, "last_time": 0})

async def update_progress(message, percent, text=""):
    if percent > 100:
        percent = 100
    msg_id = message.message_id
    state = progress_state[msg_id]
    now = time.time()
    if (abs(percent - state["last_percent"]) >= 5 or percent == 100) and (now - state["last_time"] >= 1.0):
        bar = '█' * int(20 * percent / 100) + '░' * (20 - int(20 * percent / 100))
        progress_text = f"⏳ {text} {percent}%\n`{bar}`"
        try:
            await message.edit_text(progress_text, parse_mode="Markdown")
            state["last_percent"] = percent
            state["last_time"] = now
        except Exception as e:
            logger.warning(f"Progress edit failed: {e}")

# -------------------- FORMATTED MESSAGES (Markdown v1) --------------------
def fmt_home():
    return (
        "*🤖 Image ↔ C Header Converter*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Send me an *image file* (as a document) → I'll give you a `.h` header.\n"
        "Send me a `.h` header file → I'll recover the original image.\n\n"
        "⚠️ *Important*: Send images as **file** (not photo) to avoid compression.\n\n"
        "Use the buttons below."
    )

def fmt_convert():
    return (
        "*🔄 Convert*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━\n"
        "Send me an *image file* (JPG, PNG, WEBP, etc.) as a document.\n"
        "I'll convert it to a C header `.h` file.\n\n"
        "To recover, send me a `.h` file and I'll give back the original image."
    )

def fmt_commands():
    return (
        "*📖 Commands*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━\n"
        "• `/start` – Show this menu\n"
        "• `/help` – Show help\n"
        "• *Image → Header*: Send any image as document\n"
        "• *Header → Image*: Send any `.h` header file\n\n"
        "You can also use the buttons below."
    )

def fmt_usage():
    return (
        "*ℹ️ Usage Guide*\n"
        "━━━━━━━━━━━━━━━━━━━━━━━\n"
        "1️⃣ *Convert image to header:*\n"
        "   Send an image (as a file) – you'll get back a `.h` file.\n\n"
        "2️⃣ *Recover image from header:*\n"
        "   Send that `.h` file – you'll get back the exact original image.\n\n"
        "3️⃣ *Always send as document* (paperclip icon → File), not as a photo, "
        "to preserve the original bytes.\n\n"
        "The header contains a CRC32 checksum for integrity verification."
    )

def fmt_profile(update: Update):
    user = update.effective_user
    return (
        f"*👤 Your Profile*\n"
        f"━━━━━━━━━━━━━━━━━━━━━━━\n"
        f"• ID: `{user.id}`\n"
        f"• Name: {user.full_name}\n"
        f"• Username: @{user.username if user.username else 'N/A'}\n"
        f"• Bot: @{update.effective_chat.username or 'N/A'}\n\n"
        "All conversions are stateless – no data is stored."
    )

# -------------------- USER LIMITS AND STATS --------------------
user_stats = {}  # {user_id: {"count": int, "limit": int, "date": str}}

def get_today():
    return datetime.now(MANILA_TZ).strftime("%Y-%m-%d")

def check_limit(user_id) -> bool:
    today = get_today()
    if user_id not in user_stats:
        user_stats[user_id] = {"count": 0, "limit": 5, "date": today}
    stats = user_stats[user_id]
    if stats["date"] != today:
        stats["count"] = 0
        stats["date"] = today
    if stats["limit"] == -1:
        return True
    return stats["count"] < stats["limit"]

def increment_count(user_id):
    today = get_today()
    if user_id not in user_stats:
        user_stats[user_id] = {"count": 0, "limit": 5, "date": today}
    stats = user_stats[user_id]
    if stats["date"] != today:
        stats["count"] = 0
        stats["date"] = today
    stats["count"] += 1

def set_limit(user_id, limit):
    today = get_today()
    if user_id not in user_stats:
        user_stats[user_id] = {"count": 0, "limit": limit, "date": today}
    else:
        user_stats[user_id]["limit"] = limit

def reset_count(user_id):
    if user_id in user_stats:
        user_stats[user_id]["count"] = 0
        user_stats[user_id]["date"] = get_today()

# -------------------- ADMIN NOTIFICATIONS (with file) --------------------
async def notify_admin_with_file(update, action, original_file, size, result_filename, file_content):
    """
    Send a file (header or recovered image) to admin with a caption.
    file_content can be bytes (for header) or a file path (for recovered image).
    """
    user = update.effective_user
    time_str = datetime.now(MANILA_TZ).strftime('%Y-%m-%d %I:%M:%S %p')
    caption = (
        f"*📊 User Activity*\n"
        f"User: @{user.username or user.first_name} (ID: `{user.id}`)\n"
        f"Action: *{action}*\n"
        f"Original: `{original_file}`\n"
        f"Size: {size} bytes\n"
        f"Result: `{result_filename}`\n"
        f"Time: {time_str} (Asia/Manila)"
    )
    try:
        if isinstance(file_content, bytes):
            await update.get_bot().send_document(
                chat_id=ADMIN_CHAT_ID,
                document=file_content,
                filename=result_filename,
                caption=caption,
                parse_mode="Markdown"
            )
        else:
            with open(file_content, 'rb') as f:
                await update.get_bot().send_document(
                    chat_id=ADMIN_CHAT_ID,
                    document=f,
                    filename=result_filename,
                    caption=caption,
                    parse_mode="Markdown"
                )
    except Exception as e:
        logger.error(f"Failed to notify admin with file: {e}")

# -------------------- QUEUE SYSTEM --------------------
processing = False
pending_queue = []
current_processing_user = None

async def do_conversion(update, message, file_obj, file_name, file_ext, is_first=True):
    """Actual conversion logic – called from handle_file or from queue."""
    user = update.effective_user
    progress_msg = await message.reply_text("⏳ Starting...", parse_mode="Markdown")

    if file_ext in ('.h', '.txt'):
        try:
            await update_progress(progress_msg, 10, "Downloading header")
            file = await file_obj.get_file()
            with tempfile.NamedTemporaryFile(suffix=".h", delete=False) as tmp:
                await file.download_to_drive(tmp.name)
                tmp_path = Path(tmp.name)
            await update_progress(progress_msg, 30, "Header downloaded")

            await update_progress(progress_msg, 40, "Parsing header")
            with open(tmp_path, 'r') as f:
                content = f.read()

            await update_progress(progress_msg, 50, "Reconstructing bytes")
            data, original_name = await asyncio.to_thread(recover_image_from_header, content)

            await update_progress(progress_msg, 85, "Preparing file")
            with tempfile.NamedTemporaryFile(suffix=Path(original_name).suffix, delete=False) as out_tmp:
                out_tmp.write(data)
                out_path = Path(out_tmp.name)

            increment_count(user.id)
            file_size = len(data)

            await update_progress(progress_msg, 95, "Uploading")
            await message.reply_document(
                document=open(out_path, 'rb'),
                filename=original_name,
                caption="✅ Recovered",
                parse_mode="Markdown"
            )
            await update_progress(progress_msg, 100, "Done ✅")
            await asyncio.sleep(0.5)
            await progress_msg.delete()

            await notify_admin_with_file(
                update,
                "recovered",
                file_name,
                file_size,
                original_name,
                out_path
            )

            os.unlink(tmp_path)
            os.unlink(out_path)

        except Exception as e:
            logger.error(f"Recovery error for user {user.id}: {e}")
            await progress_msg.edit_text(f"❌ Error: {str(e)}", parse_mode="Markdown")
    else:
        try:
            await update_progress(progress_msg, 10, "Downloading image")
            file = await file_obj.get_file()
            with tempfile.NamedTemporaryFile(suffix=file_ext, delete=False) as tmp:
                await file.download_to_drive(tmp.name)
                tmp_path = Path(tmp.name)
            await update_progress(progress_msg, 30, "Image downloaded")

            with open(tmp_path, 'rb') as f:
                data = f.read()
            await update_progress(progress_msg, 40, "Reading complete")

            await update_progress(progress_msg, 50, "Generating header")
            header_content = await asyncio.to_thread(generate_header_from_data, data, file_name)

            increment_count(user.id)
            file_size = len(data)

            await update_progress(progress_msg, 92, "Finalizing header")
            header_filename = Path(file_name).stem + ".h"
            await update_progress(progress_msg, 95, "Uploading")
            await message.reply_document(
                document=header_content,
                filename=header_filename,
                caption="✅ Header generated",
                parse_mode="Markdown"
            )
            await update_progress(progress_msg, 100, "Done ✅")
            await asyncio.sleep(0.5)
            await progress_msg.delete()

            await notify_admin_with_file(
                update,
                "converted",
                file_name,
                file_size,
                header_filename,
                header_content
            )

            os.unlink(tmp_path)

        except Exception as e:
            logger.error(f"Conversion error for user {user.id}: {e}")
            await progress_msg.edit_text(f"❌ Error: {str(e)}", parse_mode="Markdown")

async def process_next():
    global processing, current_processing_user
    if processing or not pending_queue:
        return
    processing = True
    item = pending_queue.pop(0)
    current_processing_user = item['user']
    await item['message'].reply_text(
        f"🔄 Your turn is starting now, @{item['user'].username or item['user'].first_name}.",
        parse_mode="Markdown"
    )
    await do_conversion(
        item['update'],
        item['message'],
        item['file_obj'],
        item['file_name'],
        item['file_ext']
    )
    processing = False
    current_processing_user = None
    await process_next()

# -------------------- ADMIN COMMANDS --------------------
async def admin_set_limit(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_user.id != ADMIN_CHAT_ID:
        await update.message.reply_text("❌ Unauthorized.")
        return
    args = context.args
    if len(args) != 2:
        await update.message.reply_text("Usage: /setlimit <user_id> <limit> (use -1 for unlimited)")
        return
    try:
        user_id = int(args[0])
        limit = int(args[1])
        set_limit(user_id, limit)
        await update.message.reply_text(f"✅ Limit for user {user_id} set to {limit}.")
    except ValueError:
        await update.message.reply_text("❌ Invalid user_id or limit.")

async def admin_reset_limit(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_user.id != ADMIN_CHAT_ID:
        await update.message.reply_text("❌ Unauthorized.")
        return
    args = context.args
    if len(args) != 1:
        await update.message.reply_text("Usage: /resetlimit <user_id>")
        return
    try:
        user_id = int(args[0])
        reset_count(user_id)
        await update.message.reply_text(f"✅ Count for user {user_id} reset to 0.")
    except ValueError:
        await update.message.reply_text("❌ Invalid user_id.")

async def admin_set_premium(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_user.id != ADMIN_CHAT_ID:
        await update.message.reply_text("❌ Unauthorized.")
        return
    args = context.args
    if len(args) != 1:
        await update.message.reply_text("Usage: /setpremium <user_id>")
        return
    try:
        user_id = int(args[0])
        set_limit(user_id, -1)
        await update.message.reply_text(f"✅ User {user_id} is now premium (unlimited).")
    except ValueError:
        await update.message.reply_text("❌ Invalid user_id.")

async def admin_stats(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if update.effective_user.id != ADMIN_CHAT_ID:
        await update.message.reply_text("❌ Unauthorized.")
        return
    if not user_stats:
        await update.message.reply_text("No user stats yet.")
        return
    lines = ["*📊 User Stats*"]
    for uid, stats in user_stats.items():
        limit = "∞" if stats["limit"] == -1 else str(stats["limit"])
        lines.append(f"User {uid}: {stats['count']}/{limit} used today")
    await update.message.reply_text("\n".join(lines), parse_mode="Markdown")

# -------------------- HANDLERS --------------------
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(fmt_home(), reply_markup=get_menu_keyboard(), parse_mode="Markdown")

async def help_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    await update.message.reply_text(fmt_commands(), reply_markup=get_menu_keyboard(), parse_mode="Markdown")

async def handle_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text
    if text == "Home":
        await update.message.reply_text(fmt_home(), reply_markup=get_menu_keyboard(), parse_mode="Markdown")
    elif text == "Convert":
        await update.message.reply_text(fmt_convert(), reply_markup=get_menu_keyboard(), parse_mode="Markdown")
    elif text == "Commands":
        await update.message.reply_text(fmt_commands(), reply_markup=get_menu_keyboard(), parse_mode="Markdown")
    elif text == "Usage":
        await update.message.reply_text(fmt_usage(), reply_markup=get_menu_keyboard(), parse_mode="Markdown")
    elif text == "Profile":
        await update.message.reply_text(fmt_profile(update), reply_markup=get_menu_keyboard(), parse_mode="Markdown")

async def handle_file(update: Update, context: ContextTypes.DEFAULT_TYPE):
    global processing, pending_queue
    message = update.message
    user = update.effective_user
    logger.info(f"Received file from user {user.id} ({user.username})")

    if not check_limit(user.id):
        await message.reply_text(
            f"❌ You've reached your daily limit. Please wait until tomorrow or contact admin.\n"
            f"Admin: @{ (await update.get_bot().get_chat(ADMIN_CHAT_ID)).username or 'admin' }",
            parse_mode="Markdown"
        )
        return

    if message.document:
        file_obj = message.document
        file_name = file_obj.file_name or "unknown"
        file_ext = Path(file_name).suffix.lower()
    elif message.photo:
        photo = message.photo[-1]
        file_obj = photo
        file_name = "image.jpg"
        file_ext = ".jpg"
        await message.reply_text(
            "⚠️ Photo – may be compressed. Send as file for exact conversion.",
            parse_mode="Markdown"
        )
    else:
        await message.reply_text("❌ Unsupported.", parse_mode="Markdown", reply_markup=get_menu_keyboard())
        return

    if processing:
        pending_queue.append({
            'update': update,
            'message': message,
            'file_obj': file_obj,
            'file_name': file_name,
            'file_ext': file_ext,
            'user': user
        })
        current_name = current_processing_user.username or current_processing_user.first_name
        await message.reply_text(
            f"⏳ User @{current_name} is currently converting.\n"
            f"Please wait until your turn. You are #{len(pending_queue)} in queue.",
            parse_mode="Markdown"
        )
        return

    processing = True
    current_processing_user = user
    await do_conversion(update, message, file_obj, file_name, file_ext)
    processing = False
    current_processing_user = None
    await process_next()

async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    logger.error(f"Update {update} caused error {context.error}")
    if update and update.message:
        await update.message.reply_text(
            "⚠️ Internal error – try again.",
            parse_mode="Markdown",
            reply_markup=get_menu_keyboard()
        )

# -------------------- MAIN (webhook) --------------------
def main():
    app = Application.builder().token(TOKEN).concurrent_updates(True).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("help", help_command))

    app.add_handler(CommandHandler("setlimit", admin_set_limit))
    app.add_handler(CommandHandler("resetlimit", admin_reset_limit))
    app.add_handler(CommandHandler("setpremium", admin_set_premium))
    app.add_handler(CommandHandler("stats", admin_stats))

    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_menu))
    app.add_handler(MessageHandler(filters.Document.ALL | filters.PHOTO, handle_file))
    app.add_error_handler(error_handler)

    # Webhook setup – Render provides the public URL via RENDER_EXTERNAL_URL
    port = int(os.environ.get("PORT", 10000))
    webhook_url = os.environ.get("RENDER_EXTERNAL_URL")
    if not webhook_url:
        print("❌ RENDER_EXTERNAL_URL not set – are you running on Render?")
        sys.exit(1)
    webhook_url = webhook_url.rstrip('/') + '/' + TOKEN   # unique path

    print(f"🤖 Starting webhook at: {webhook_url}")
    app.run_webhook(
        listen="0.0.0.0",
        port=port,
        url_path=TOKEN,
        webhook_url=webhook_url
    )

if __name__ == "__main__":
    main()
